<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CostElement;
use App\Models\CostTee;

class CostTeeSeederOneForAll extends Seeder
{
    public function run()
    {
        $data = [
            ['code' => 'KI010101', 'description' => 'Peneriaan Booking Fee'],
            ['code' => 'KI020101', 'description' => 'Penerimaan dari Down Payment'],
            ['code' => 'KI030101', 'description' => 'Biaya Kelebihan Tanah'],
            ['code' => 'KI030201', 'description' => 'Biaya Penambahan Spek bangunan'],
            ['code' => 'KI030301', 'description' => 'Biaya Selisih KPR'],
            ['code' => 'KI040101', 'description' => 'Penerimaan KPR'],
            ['code' => 'KI050101', 'description' => 'Share Capital Ordinary (Kantor Pusat / Modal Perseroan)'],
            ['code' => 'KI060101', 'description' => 'Penerimaan dari Penjulan Barang dan Jasa Kerja'],
            ['code' => 'KI060201', 'description' => 'Penerimaan dari Bunga Bank'],
            ['code' => 'KI070101', 'description' => 'Pencairan Piutang Retensi Bestek (IMB, Listrik, Air dan Jalan)'],
            ['code' => 'KI070102', 'description' => 'Pelunasan Piutang DP dan Selisih DP (Down Payment)'],
            ['code' => 'KI070103', 'description' => 'Pelunasan Piutang Biaya Kelebihan Tanah'],
            ['code' => 'KI070104', 'description' => 'Pelunasan Piutang Biaya Penambahan Spek Bangunan'],
            ['code' => 'KI070105', 'description' => 'Pelunasan Piutang Selisih KPR'],
            ['code' => 'KI070106', 'description' => 'Pelunasan Piutang Berelasi'],
            ['code' => 'KI070107', 'description' => 'Pelunasan Piutang Pihak Ketiga'],
            ['code' => 'KI090101', 'description' => 'Hutang Bank (Pencairan Dana Bank)'],
            ['code' => 'KI100101', 'description' => 'Hutang Pihak Ketiga (Pinjaman Pihak Ketiga)'],
            ['code' => 'KI110101', 'description' => 'Hutang Berelasi (Setoran dari Mitra Relasi atau Pemegang Saham)'],
            ['code' => 'KO010101', 'description' => 'Biaya Perizinan'],
            ['code' => 'KO010102', 'description' => 'Biaya Pembebasan Tanah'],
            ['code' => 'KO010103', 'description' => 'Biaya Perencanaan'],
            ['code' => 'KO010104', 'description' => 'Biaya Pematangan Lahan'],
            ['code' => 'KO010105', 'description' => 'Biaya Making Badan Jalan'],
            ['code' => 'KO010106', 'description' => 'Biaya Sertifikat Induk'],
            ['code' => 'KO010201', 'description' => 'Pekerjaan Jalan Utama  & Jalan Komplex'],
            ['code' => 'KO010202', 'description' => 'Saluran Air Utama & Saluran Kawasan'],
            ['code' => 'KO010203', 'description' => 'Fasilitas Kawasan (Gerbang, Taman dan bak sampah )'],
            ['code' => 'KO010204', 'description' => 'Jaringan Listrik'],
            ['code' => 'KO010205', 'description' => 'Air Bersih Induk'],
            ['code' => 'KO010501', 'description' => 'Biaya Alat Peraga Marketing'],
            ['code' => 'KO010502', 'description' => 'Insentif / Briging Fee / Fee Marketing'],
            ['code' => 'KO010503', 'description' => 'Biaya Operasional marketing'],
            ['code' => 'KO010601', 'description' => 'Pajak Bayar Dimuka ( PNBP, BPHTB, PPh Pasal 23,PPh Pasal 21 dan PPN )'],
            ['code' => 'KO010701', 'description' => 'Biaya Lainnya yang berhubungan dengan proyek'],
            ['code' => 'KO010801', 'description' => 'Upah Buruh Kerja Harian Lepas'],
            ['code' => 'KO020101', 'description' => 'Biaya Gaji Karyawan'],
            ['code' => 'KO020102', 'description' => 'Biaya Ansuransi Kesehatan'],
            ['code' => 'KO020103', 'description' => 'Biaya Ansuransi Kecelakaan Kerja'],
            ['code' => 'KO020104', 'description' => 'Biaya Pengobatan'],
            ['code' => 'KO020105', 'description' => 'Biaya Pakaian & Peralatan Keselamatan Kerja'],
            ['code' => 'KO020106', 'description' => 'Bonus Jasa Produksi'],
            ['code' => 'KO020201', 'description' => 'Biaya Telepon / Pulsa'],
            ['code' => 'KO020202', 'description' => 'Biaya Listrik dan Energy'],
            ['code' => 'KO020203', 'description' => 'Biaya adm & Alat Tulis Kantor'],
            ['code' => 'KO020204', 'description' => 'Biaya Perjalanan Dinas & Rapat'],
            ['code' => 'KO020205', 'description' => 'Biaya Perawatan Inventaris'],
            ['code' => 'KO020206', 'description' => 'Biaya Sumbangan / Partisipasi (CSR)'],
            ['code' => 'KO020207', 'description' => 'Biaya Intertaiment relasi'],
            ['code' => 'KO020208', 'description' => 'Bahan Bakar'],
            ['code' => 'KO020209', 'description' => 'Biaya Operasional Kantor Lain - lain'],
            ['code' => 'KO020301', 'description' => 'Pengadaan Mesin dan Peralatan Proyek (Mesin Produksi)'],
            ['code' => 'KO020302', 'description' => 'Pengadaan Peralatan dan Perabot Kantor'],
            ['code' => 'KO020401', 'description' => 'Biaya Lain - lain yang berhubungan dgn operasional'],
            ['code' => 'KO030101', 'description' => 'Biaya Administrasi Pinjaman (Notaris, Adm, Aprisal dll)'],
            ['code' => 'KO030201', 'description' => 'Pembayaran Bunga Pinjaman 12,5 % per Tahun'],
            ['code' => 'KO030301', 'description' => 'Pengembalian Pokok Pinjaman Bank (Pot. KPR)'],
            ['code' => 'KO030401', 'description' => 'Pengembalian Pinjaman Pihak Ketiga'],
            ['code' => 'KO030402', 'description' => 'Pengembalian Pinjaman Pihak Berelasi'],
            ['code' => 'KO030501', 'description' => 'Biaya Pengembalian Uang Muka'],
            ['code' => 'KO040101', 'description' => 'Piutang (Dana Ditahan) Retensi Bestek (IMB, Listrik, Air dan Jalan)'],
            ['code' => 'KO040102', 'description' => 'Piutang DP dan Selisih DP (Down Payment)'],
            ['code' => 'KO040103', 'description' => 'Piutang Biaya Kelebihan Tanah'],
            ['code' => 'KO040104', 'description' => 'Piutang Biaya Penambahan Spek Bangunan'],
            ['code' => 'KO040105', 'description' => 'Piutang Selisih KPR'],
            ['code' => 'KO040106', 'description' => 'Piutang Berelasi'],
            ['code' => 'KO040107', 'description' => 'Piutang Pihak Ketiga'],
            ['code' => 'KO050101', 'description' => 'Setor ke Kantor Pusat'],
            ['code' => 'KO0103C3609', 'description' => 'Biaya SARAN Blok C No 9'],
            ['code' => 'KO0103C3610', 'description' => 'Biaya SARAN Blok C No 10'],
            ['code' => 'KO0103C3611', 'description' => 'Biaya SARAN Blok C No 11'],
            ['code' => 'KO0103C3612', 'description' => 'Biaya SARAN Blok C No 12'],
            ['code' => 'KO0103D3601', 'description' => 'Biaya SARAN Blok D No 1'],
            ['code' => 'KO0103D3602', 'description' => 'Biaya SARAN Blok D No 2'],
            ['code' => 'KO0103D3603', 'description' => 'Biaya SARAN Blok D No 3'],
            ['code' => 'KO0103D3604', 'description' => 'Biaya SARAN Blok D No 4'],
            ['code' => 'KO0103E3601', 'description' => 'Biaya SARAN Blok E No 1'],
            ['code' => 'KO0103E3602', 'description' => 'Biaya SARAN Blok E No 2'],
            ['code' => 'KO0103E3603', 'description' => 'Biaya SARAN Blok E No 3'],
            ['code' => 'KO0103E3604', 'description' => 'Biaya SARAN Blok E No 4'],
            ['code' => 'KO0103E3605', 'description' => 'Biaya SARAN Blok E No 5'],
            ['code' => 'KO0103E3606', 'description' => 'Biaya SARAN Blok E No 6'],
            ['code' => 'KO0103E3607', 'description' => 'Biaya SARAN Blok E No 7'],
            ['code' => 'KO0103E3608', 'description' => 'Biaya SARAN Blok E No 8'],
            ['code' => 'KO0103E3609', 'description' => 'Biaya SARAN Blok E No 9'],
            ['code' => 'KO0103E3610', 'description' => 'Biaya SARAN Blok E No 10'],
            ['code' => 'KO0103E3611', 'description' => 'Biaya SARAN Blok E No 11'],
            ['code' => 'KO0103E3612', 'description' => 'Biaya SARAN Blok E No 12'],
            ['code' => 'KO0103F3601', 'description' => 'Biaya SARAN Blok F No 1'],
            ['code' => 'KO0103F3602', 'description' => 'Biaya SARAN Blok F No 2'],
            ['code' => 'KO0103F3603', 'description' => 'Biaya SARAN Blok F No 3'],
            ['code' => 'KO0103F3604', 'description' => 'Biaya SARAN Blok F No 4'],
            ['code' => 'KO0103F3605', 'description' => 'Biaya SARAN Blok F No 5'],
            ['code' => 'KO0103F3606', 'description' => 'Biaya SARAN Blok F No 6'],
            ['code' => 'KO0103F3607', 'description' => 'Biaya SARAN Blok F No 7'],
            ['code' => 'KO0103F3608', 'description' => 'Biaya SARAN Blok F No 8'],
            ['code' => 'KO0103F3609', 'description' => 'Biaya SARAN Blok F No 9'],
            ['code' => 'KO0103F3610', 'description' => 'Biaya SARAN Blok F No 10'],
            ['code' => 'KO0103F3611', 'description' => 'Biaya SARAN Blok F No 11'],
            ['code' => 'KO0103F3612', 'description' => 'Biaya SARAN Blok F No 12'],
            ['code' => 'KO0103F3613', 'description' => 'Biaya SARAN Blok F No 13'],
            ['code' => 'KO0103F3614', 'description' => 'Biaya SARAN Blok F No 14'],
            ['code' => 'KO0103G3601', 'description' => 'Biaya SARAN Blok G No 1'],
            ['code' => 'KO0103G3602', 'description' => 'Biaya SARAN Blok G No 2'],
            ['code' => 'KO0103G3603', 'description' => 'Biaya SARAN Blok G No 3'],
            ['code' => 'KO0103G3604', 'description' => 'Biaya SARAN Blok G No 4'],
            ['code' => 'KO0103G3605', 'description' => 'Biaya SARAN Blok G No 5'],
            ['code' => 'KO0103G3606', 'description' => 'Biaya SARAN Blok G No 6'],
            ['code' => 'KO0103G3607', 'description' => 'Biaya SARAN Blok G No 7'],
            ['code' => 'KO0103G3608', 'description' => 'Biaya SARAN Blok G No 8'],
            ['code' => 'KO0103G3609', 'description' => 'Biaya SARAN Blok G No 9'],
            ['code' => 'KO0103G3610', 'description' => 'Biaya SARAN Blok G No 10'],
            ['code' => 'KO0103G3611', 'description' => 'Biaya SARAN Blok G No 11'],
            ['code' => 'KO0103G3612', 'description' => 'Biaya SARAN Blok G No 12'],
            ['code' => 'KO0103G3613', 'description' => 'Biaya SARAN Blok G No 13'],
            ['code' => 'KO0103G3614', 'description' => 'Biaya SARAN Blok G No 14'],
            ['code' => 'KO0103G3615', 'description' => 'Biaya SARAN Blok G No 15'],
            ['code' => 'KO0103G3616', 'description' => 'Biaya SARAN Blok G No 16'],
            ['code' => 'KO0103G3617', 'description' => 'Biaya SARAN Blok G No 17'],
            ['code' => 'KO0103G3618', 'description' => 'Biaya SARAN Blok G No 18'],
            ['code' => 'KO0103H3601', 'description' => 'Biaya SARAN Blok H No 1'],
            ['code' => 'KO0103H3602', 'description' => 'Biaya SARAN Blok H No 2'],
            ['code' => 'KO0103H3603', 'description' => 'Biaya SARAN Blok H No 3'],
            ['code' => 'KO0103H3604', 'description' => 'Biaya SARAN Blok H No 4'],
            ['code' => 'KO0103H3605', 'description' => 'Biaya SARAN Blok H No 5'],
            ['code' => 'KO0103H3606', 'description' => 'Biaya SARAN Blok H No 6'],
            ['code' => 'KO0103H3607', 'description' => 'Biaya SARAN Blok H No 7'],
            ['code' => 'KO0103H3608', 'description' => 'Biaya SARAN Blok H No 8'],
            ['code' => 'KO0103H3609', 'description' => 'Biaya SARAN Blok H No 9'],
            ['code' => 'KO0103H3610', 'description' => 'Biaya SARAN Blok H No 10'],
            ['code' => 'KO0103H3611', 'description' => 'Biaya SARAN Blok H No 11'],
            ['code' => 'KO0103H3612', 'description' => 'Biaya SARAN Blok H No 12'],
            ['code' => 'KO0103H3613', 'description' => 'Biaya SARAN Blok H No 13'],
            ['code' => 'KO0103H3614', 'description' => 'Biaya SARAN Blok H No 14'],
            ['code' => 'KO0103I3601', 'description' => 'Biaya SARAN Blok I No 1'],
            ['code' => 'KO0103I3602', 'description' => 'Biaya SARAN Blok I No 2'],
            ['code' => 'KO0103I3603', 'description' => 'Biaya SARAN Blok I No 3'],
            ['code' => 'KO0103I3604', 'description' => 'Biaya SARAN Blok I No 4'],
            ['code' => 'KO0103I3605', 'description' => 'Biaya SARAN Blok I No 5'],
            ['code' => 'KO0103I3606', 'description' => 'Biaya SARAN Blok I No 6'],
        ];

        foreach ($data as $item) {
            $teeCode = $item['code'];
            $elementCode = substr($teeCode, 0, 6); // ambil 6 digit pertama

            $costElement = CostElement::where('cost_element_code', $elementCode)->first();

            if (!$costElement) {
                echo "Cost Element $elementCode tidak ditemukan, skip...\n";
                continue;
            }

            CostTee::create([
                'perumahan_id' => $costElement->perumahan_id,
                'cost_element_code' => $elementCode,
                'cost_tee_code' => $teeCode,
                'description' => $item['description'],
            ]);
        }
    }
}
